### ISSUE TITLE
The new 1.5.0 version of fabric Right Click Harvest mod crash on multiplayer

### ISSUE THREAD

**Issue by serioos** [JamCoreModding/RightClickHarvestFabric#4]
The mod crashes the client when I try harvesting by right clicking on a server. I tried it on sugarcane and wheat and it crashed me both times.

Here's the crash logs for both crashes:

https://pastebin.com/dpTdLfJZ

https://pastebin.com/gWDzN3FU

**Comment by Jamalam360** [comment]
Thanks, looking into it now

**Comment by Jamalam360** [comment]
I can't reproduce this, do you know what version of Fabric Loader you're using?

**Comment by Jamalam360** [comment]
If you're using an outdated version perhaps you need to update (see #2 for the issue, it's now solved when if update your loader)

**Comment by serioos** [comment]
I'm using fabric loader 0.12.3 with fabric API of 0.41.3.

But thanks for the answer. I'll see if updating them will help.

**Comment by Jamalam360** [comment]
Hi

Sorry it's so late; is this still an issue?

**Comment by Jamalam360** [comment]
Hi

Sorry it's so late; is this still an issue?

**Comment by Jamalam360** [comment]
Stale
