### ISSUE TITLE
Works good in 1.18.2

### ISSUE THREAD

**Issue by jarocajavi** [JamCoreModding/RightClickHarvestFabric#8]
Just that ;)

**Comment by Jamalam360** [comment]
Are you saying it _does_ work in 1.18.2? I can tag it as 1.18.2 on curseforge then

**Comment by jarocajavi** [comment]
Yep, I posted here because the comment space is lock in curseforge for your mod ;) 

Thanks for the work. :)

**Comment by Jamalam360** [comment]
Thanks! I tagged it as 1.18.2 compatible on curseforge
