### ISSUE TITLE
Jablib

### ISSUE THREAD

**Issue by Romz24** [JamCoreModding/RightClickHarvestFabric#9]
I updated the version of your mod, when I try to enter the game, this error pops up.
Can you add this library to the mod, or write in curseforge that it is required to work?

![image](https://user-images.githubusercontent.com/2458113/168818982-0c53c2e1-e240-4c94-9c40-bf27d065acd6.png)

**Comment by Jamalam360** [comment]
Sorry it should say that it's required already on curseforge, but it's an automatic system that uploads the files, so I'll check

**Comment by Jamalam360** [comment]
I've added the dependency on curseforge
